DROP TABLE IF EXISTS t_test;
DROP TABLE IF EXISTS temp;
DROP TABLE IF EXISTS fTemp;
DROP TABLE IF EXISTS hTemp;
DROP TABLE IF EXISTS t_options;
DROP TABLE IF EXISTS t_widgetConfig;
DROP TABLE IF EXISTS tt;